### ISSUE TITLE
请教：RocketMQ灰度切换destination导致订阅关系不一致，有什么解决思路吗？

### ISSUE THREAD

**Issue by for2cold** [Nepxion/DiscoveryContrib#1]
RocketMQ要求订阅关系一致，即同一个消费者 Group ID 下所有 Consumer 实例所订阅的 Topic、Group ID、Tag 必须完全一致。一旦订阅关系不一致，消息消费的逻辑就会混乱，甚至导致消息丢失。
请教一下有什么解决思路哈？
![image](https://user-images.githubusercontent.com/2671804/104559536-80ff9180-567f-11eb-9d19-eff09a10c936.png)

**Comment by HaojunRen** [comment]
那块功能目前没有作为重点演进
